### ISSUE TITLE
[FEATURE] Todo 도메인 구현

### ISSUE THREAD

**Issue by bombo-dev** [Team-Reviser/Reviser-back#3]
## ✅ 어떤 기능인가요?

Reviser 애플리케이션의 Todo는 다음과 같은 요구사항을 충족해야합니다.
1. 일 별로 Todo를 생성 할 수 있다.
2. Todo에 대한 플래닝을 정할 수 있다. 10m 단위
3. Todo는 복습 전략에 따라 복습 일자를 유저에게 리마인더 해 줄 수 있다.
4. 이미 한 번 이라도 복습 전략에 따라 복습이 진행되고 있다면 해당 Todo의 복습 전략은 변경이 불가능하다.
5. 완료된 Todo는 제거가 불가능하다.
6. 당일 만들어진 Todo는 제거가 가능하다.
7. TODO는 기본적으로 3개의 상태를 가진다. 
  - CREATED
  - PROGRESS
  - REVIEWING
  - COMPLETED
9. Todo의 내용은 중간에 수정이 가능하다.
10. Todo는 Detail 하게 작성이 가능하다.

> 추가하려는 기능에 대해 간결하게 설명해주세요

## 작업 상세 내용

- [ ] Todo Domain 구현
- [ ] Todo Domain에 따른 예외 케이스 구현 및 테스트
- [ ] 복습 전략 구현

## 참고할만한 자료(선택)
- [에빙하우스 망각곡선](https://brunch.co.kr/@linecard/617)
- [토리파 공부법](https://blog.naver.com/einsam0313/222457681586)

**Comment by bombo-dev** [comment]
# Title Test 구현 이슈
도메인의 Title 필드 검증을 위한 테스트를 작성 할 때 null or blank 테스트를 작성해야 했다.  
먼저 떠오른 방법은 junit이 제공해주는 `@ValueSource`를 사용하는 방식이었다. 테스트 코드 작성은 다음과 같았다.

```java
    @DisplayName("Todo Title은 공백이거나 null 이면 생성 시 예외가 발생한다.")
    @ValueSource(strings = {"", " ", null}
    @ParameterizedTest
    void constructTitleWithIsBlank(String input) {
        // given

        // when & then
        assertThatThrownBy(() -> {
            new Title(input);
        }).isInstanceOf(TitleIsNotBlankException.class)
                .hasMessage("리뷰의 타이틀은 null 이거나 공백 일 수 없습니다.");
    }
```

하지만, null이 들어가는 부분에서 **compileError**가 발생했다. 따라서, 이를 해결하기 위해 `@MethodSource` 를 사용할까 하였다. 만약 `@MethodSource`를 사용한다면 코드는 다음과 같이 변하게 될 것이다.

```java
    @DisplayName("Todo Title은 공백이거나 null 이면 생성 시 예외가 발생한다.")
    @MethodSource("nullOrIsBlank");
    @ParameterizedTest
    void constructTitleWithIsBlank(String input) {
        // given

        // when & then
        assertThatThrownBy(() -> {
            new Title(input);
        }).isInstanceOf(TitleIsNotBlankException.class)
                .hasMessage("리뷰의 타이틀은 null 이거나 공백 일 수 없습니다.");
    }

static private Stream<String> nullOrIsBlank() {
  return Stream.of("", " ", null);
}
```
이러한 방식 또한 성공적인 테스트를 뱉어내지만 혹시 몰라 검색을 해보게 되었다. 그리고 JUnit에서 제공해주는 또 다른 애노테이션인 `NullAndEmptySource`의 존재를 알게 되었다. 최종 테스트 코드는 다음과 같이 변하게 되었다.

```java
    @DisplayName("Todo Title은 공백이거나 null 이면 생성 시 예외가 발생한다.")
    @NullAndEmptySource
    @ParameterizedTest
    void constructTitleWithIsBlank(String input) {
        // given

        // when & then
        assertThatThrownBy(() -> {
            new Title(input);
        }).isInstanceOf(TitleIsNotBlankException.class)
                .hasMessage("리뷰의 타이틀은 null 이거나 공백 일 수 없습니다.");
    }
```

**Comment by bombo-dev** [comment]
# 파라미터에 final 키워드를 붙일까?
코드를 짜면서 계속해서 안정성 있는 코드, 확장 가능한 코드에 대해서 고민을 하고 있다.
그러다가 파라미터에 final 키워드를 붙이는 것은 어떨까 하는 생각이 들었다.

다음은 이전에 만들었던 TodoDetails 클래스의 내부 로직이다.
```java
package com.bombo.reviser.core.todo.domain;

import com.bombo.reviser.common.error.ErrorCode;
import com.bombo.reviser.core.todo.exception.DescriptionIsNotNullException;
import com.bombo.reviser.core.todo.exception.TitleIsNotBlankException;
import com.bombo.reviser.core.todo.exception.WriteDateTimeIsNotNullException;
import lombok.Getter;

import java.time.LocalDateTime;

@Getter
public class TodoDetails {

    private static final String TITLE_NULL_EXCEPTION_MSG = "Title은 null 일 수 없습니다.";
    private static final String DESCRIPTION_NULL_EXCEPTION_MSG = "Description은 null 일 수 없습니다.";

    private Title title;
    private Description description;
    private final LocalDateTime writeDateTime;
    private LocalDateTime modifiedDateTime;

    public TodoDetails(Title title, Description description, LocalDateTime writeDateTime) {
        validConstructor(title, description, writeDateTime);
        this.title = title;
        this.description = description;
        this.writeDateTime = writeDateTime;
        this.modifiedDateTime = writeDateTime;
    }

    public void updateDetail(TodoDetails updateDetails, LocalDateTime now) {
        this.title = updateDetails.title;
        this.description = updateDetails.description;
        this.modifiedDateTime = now;
    }

    private void validContstructor(Title title, Description description, LocalDateTime writeDateTime) {
        // ...
    }
}
```
해당 필드들에 final 키워드를 표시해주는 것으로 인해서 생길 수 있는 효과가 무엇인지에 대해서 먼저 생각을 해봤다.
자바는 우리가 익히 알고 있는 Call By Reference를 지원하지 않는다. 따라서, 다음과 같은 코드가 있을 때 실제 값이 대체되지 않는다.

```java
main() {
    Title title = new Title("제목");
    update(title);
    System.out.println(title.getTitle()); // "제목"
}

update(Title title) {
    title = new Title("수정된 제목");
}
```

기본적으로 값을 복사해서 전달하고, 기존에 복사해서 전달 된 객체에 새로이 만들어진 객체의 주소값을 새로 할당하도록 되어있는 구조이기 때문에 위의 방식이 동작하지 않는다.

만약, final 키워드를 사용하게 된다면 위와 같이 파라미터로 전달받은 객체에 새로이 만든 객체의 주소 값을 넣어주는 것을 방지해 줄 수 있다.
하지만, 보통 final 키워드를 사용하는 목적은 내부의 값이 변경되지 않았으면 하는 바램이 많을 것이다. final 키워드를 사용하더라도 참조 형태의 객체 내부의 값은 파라미터에 final 키워드를 붙이더라도 변경이 가능하다. 별로 큰 이점이 오지 않는 것 같다.

다만, 기본값 형태에 대해서는 말이 다를 수 있을 것 같다. 변경되지 말아야 할 기본 값이 존재한다면, 해당 값에는 final 키워드를 붙여 코드의 안정성을 더 높일 수 있을 것으로 생각이 된다.

따라서, 기존의 TodoDetails에는 들어오는 인자들이 참조형 타입이기 때문에 final 키워드를 붙이지 않았다. 만약 기본 값을 사용하는 타입이 있다면 final 키워드를 붙이는 것으로 가져가야겠다는 생각이다.
